#!/bin/bash

#ln -s /lib/i386-linux-gnu/libssl.so.1.0.0 /lib/i386-linux-gnu/libssl3.so

awk -F: '{if ($3>=1000 && $3<2000) {system("/opt/junior/create_shortcut.sh " $1)}}' /etc/passwd
update-menus


message1="All users have been added to the \"dialout\" group.";
message2="Please login/logout to apply the changes before you start working with ScratchDuino2.";

zenity --info --text "$message1\n\n$message2"
notify-send "$message1" "$message2"



